### ISSUE TITLE
CloseHandle and lastrequest_gungolf

### ISSUE THREAD

**Issue by Caaine** [dataviruset/sm-hosties#14]
Hey
error log for me 

L 08/17/2015 - 04:03:11: Info (map "ba_jail_minecraftparty_v6") (file "errors_20150817.log")
L 08/17/2015 - 04:03:11: [SM] Native "CloseHandle" reported: Handle cad906e9 is invalid (error 3)
L 08/17/2015 - 04:03:11: [SM] Displaying call stack trace for plugin "sm_hosties.smx":
L 08/17/2015 - 04:03:11: [SM]   [0]  Line 258, hosties/muteprisoners.sp::MutePrisoners_RoundEnd()

gungolf:
The Weapons has Ammo 

shotgunwar:
add the other Shotguns = Mag-7, Nova and Sawed-off

greetz 
Caaine

**Comment by Bara20** [comment]
btw. GunGolf and ShotgunWar aren't a part of this repo.

**Comment by data-bomb** [comment]
The only relevant issue here is the mute error which is patched by #24.  The other two discussion points do not apply.  Can be closed in full.
