### ISSUE TITLE
Sometimes person is rebel after round 

### ISSUE THREAD

**Issue by PreFix** [dataviruset/sm-hosties#16]
Hello. I seen branch with this fix, but it's outdated, when it be merged with default one? I have this issue like person who made this branch.

**Comment by PreFix** [comment]
https://github.com/dataviruset/sm-hosties/commit/b6efbdde4fc89e76cc444c60204e6699a2d74ff3

someone please

**Comment by data-bomb** [comment]
Commit https://github.com/dataviruset/sm-hosties/commit/05d25a407211d576cd8a89f56e818702a1306711 manually merges this into main branch
