### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Kailo97** [dataviruset/sm-hosties#33]
In [LastRequest_WeaponFire](https://github.com/dataviruset/sm-hosties/blob/master/addons/sourcemod/scripting/hosties/lastrequest.sp#L1627) in hosties/lastrequest.sp
```
public LastRequest_WeaponFire(Handle:event, const String:name[], bool:dontBroadcast)
{
	...
	else if (type == LR_Shot4Shot)
	{
		...
		if (StrEqual(LR_WeaponName, FiredWeapon)) // This line
		{
			...
		}
		...
	{
	...
}
```
In CSGO different weapons can have same class, like: revolver->deagle; usp_silencer->hkp2000. You can't play S4S using Revolver and USP-S — you will be killed after the first shot.

**Comment by SHAREN** [comment]
would not it be sm_hosties in conflict with this plugin? https://forums.alliedmods.net/showthread.php?t=236199

**Comment by data-bomb** [comment]
Thanks Kailo97, I was just speaking with some of the other devs on why we're doing the string check there anyway.  The M4M checks are much more efficient although we should be using EntRef translations like we do in Russian Roulette for these as well.

https://github.com/dataviruset/sm-hosties/commit/370b4302eac7f7140ef7acbcadce15064b7cb6e5 closes this.
