### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by Shoxxo** [dataviruset/sm-hosties#34]
I am interesting to translate from englisch to German. Write me a PM in AlliedModders under my nickname Chaya_

**Comment by Bara20** [comment]
Tun tu es doch einfach und erstelle dafür ein Pull Request. Also warum extra eine PN schreiben bzw. haben wollen, um sich wichtig darstellen zu wollen?

**Comment by Shoxxo** [comment]
Ich erstelle kein Pullrequest, ich mach wenn offiziell mit oder ebend nicht. Aber ich habe keine Zeit für ein Pullrequest!

**Comment by data-bomb** [comment]
Warst du hast Zeit für Übersetzungaber nicht Pullrequest??

**Comment by Shoxxo** [comment]
Ôkay, ich drücke mich einmal anders aus, ich möchte mein Profil sauber halten und nicht 100 andere Clones haben!

**Comment by Bara20** [comment]
Close?
Seems to be useless.

**Comment by data-bomb** [comment]
Closing.  @Shoxxo can always send a pull request if he finishes.
