### ISSUE TITLE
Problem with "FollowCSGOServerGuidelines"

### ISSUE THREAD

**Issue by Totenfluch** [dataviruset/sm-hosties#39]
```
 L 03/04/2016 - 21:38:56: [SM] Native "SetEntProp" reported: Cannot set m_iItemDefinitionIndex with "FollowCSGOServerGuidelines" option enabled.
L 03/04/2016 - 21:38:56: [SM] Displaying call stack trace for plugin "sm_hosties.smx":
L 03/04/2016 - 21:38:56: [SM]   [0]  Line 5204, D:\Matt\Documents\SourceMod\sm-hosties\hosties/lastrequest.sp::Timer_Countdown()

```

This Results in most LR's not beeing playable

kind regards

**Comment by data-bomb** [comment]
Totenfluch, this appears to be a safety precaution documented here:
https://forums.alliedmods.net/showthread.php?p=2399041

To summarize, Valve has decided that changing the ammo for weapons will get your server token banned and SourceMod is preventing that from happening.  Perhaps we could investigate another method later but in the mean time the LRs will not work.

**Comment by Totenfluch** [comment]
Could you change the methods to something that is not prevented?
Most of us are much more comfortable running a Server with this option turned on.

If you don't have the time I'll eventually figure out a way myself but if you do have the time
please provide a fix for us :)

**Comment by data-bomb** [comment]
Totenfluch, test the following on CS:GO:
https://github.com/dataviruset/sm-hosties/commit/329ebe7b6836e23b69d359885b2c5ea7415592dc

1) Last Request with Dodgeball
- Verify CT receives flashbang at the start
- Verify T receives flashbang at the start
- Verify CT receives flashbang each time they throw
- Verify T receives flashbang each time they throw

2) Last Request with NoScope
- Go through each menu option, verify CT and T receive their weapons
- Verify ammo is set to 99
