### ISSUE TITLE
IP Change

### ISSUE THREAD

**Issue by Bara20** [dataviruset/sm-hosties#41]
@dataviruset can you change the variable (B_FTP_HOST) on travis to "ftp.csgottt.com"? I plan a hosting change with a new ip (and a subdomain is one of the best solution).

**Comment by dataviruset** [comment]
Change done, please confirm that it works :)

**Comment by Bara20** [comment]
Our community moved to a new hoster. I think this afternoon/tonight.(btw. it's 1am).

**Comment by Bara20** [comment]
Looks good. Try it.

**Comment by dataviruset** [comment]
Seems it doesn't work, just merged a pull request which triggered a build, but it failed after running for 2 hours(!)... connection timeout?
https://travis-ci.org/dataviruset/sm-hosties/jobs/120041566

**Comment by Bara20** [comment]
Try now please.

**Comment by Bara20** [comment]
Looks good now (TTT builds for example).
