### ISSUE TITLE
1.8 Deprecated Functions

### ISSUE THREAD

**Issue by data-bomb** [dataviruset/sm-hosties#43]
FindSendPropOffs is deprecated and causing errors on 1.8 branch of SM.  Will need to fix these for future builds.

**Comment by Bara20** [comment]
> #pragma deprecated Use FindSendPropInfo instead, or HasEntProp if you just want to check for existence.
FindSendPropInfo without any changes, just change FindSendPropOffs to FindSendPropInfo
