### ISSUE TITLE
Strips weapons when disabled..

### ISSUE THREAD

**Issue by condolent** [dataviruset/sm-hosties#45]
I think it's hosties on my server that strips weapons when round starts. A map I'm playing is supposed to have weapons in CT spawn (ba_jail_alpha) but they're not there. I've disabled strips on ban/kick/slay and no changes. 

Launching the map on a local without any plugins (just default by typing "map <mapname>" in console and the weapons are there.

Is there a command or something that I've missed??

**Comment by bchewy** [comment]
Is this cvar set to 1?
mp_weapons_allow_map_placed

**Comment by condolent** [comment]
Thanks! That did it, had no idea they changed that to default to 0

**Comment by bchewy** [comment]
no problem, you can email me at brian@rthaurg.net if you have any problems
with the jb server
