### ISSUE TITLE
Bugs - CSGO

### ISSUE THREAD

**Issue by ngx3** [dataviruset/sm-hosties#46]
Mute Ts for # of seconds only works sometimes. Only a handful of LRs work. Some LR games such as shot4shot kills the player who shoots first, tried with both CT and T. Dodgeball doesn't work period. etc..

I've disabled them most of them. Just wanted to report the bugs.

**Comment by data-bomb** [comment]
All of these issues are fixed if you use the latest version.  In the future, only one bug per issue.
