### ISSUE TITLE
OnAvailableLR Forward Does Not Fire at Round Start

### ISSUE THREAD

**Issue by data-bomb** [dataviruset/sm-hosties#48]
In uncommon situations where sm_hosties_lr_ts_max is set high or the server has low population, OnAvailableLR is not firing until someone dies, which may be too late for other plugins.

**Comment by data-bomb** [comment]
https://github.com/dataviruset/sm-hosties/commit/10bbaaacdca735cdb9977a3be9f33af3f8dffd23 is proposed to fix this bug

**Comment by data-bomb** [comment]
This could benefit plugins using OnAvailbleLR forward @shanapu

**Comment by shanapu** [comment]
round_freeze_end, nice idea! 
Thanks for the fast fix! and good communication!
