### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by Caaine** [dataviruset/sm-hosties#55]
Game: CSGO
Hosties: Beta Build

https://crash.limetech.org/ri6lwzyfgcym
https://crash.limetech.org/mrp6hj5lc4hi
https://crash.limetech.org/ai5skupr67qh
https://crash.limetech.org/awz3d6bwoedw

Server crashing.. 

my CFG:

// Enables that players can not attack players in LR and players in LR can not attack players outside LR: 0 - disable, 1 - enable
// -
// Default: "0"
// Minimum: "0.000000"
// Maximum: "1.000000"
sm_hosties_lr_damage "1"

**Comment by data-bomb** [comment]
What is the Hosties version and build/commit that you are running on your server?  Provide the steps to reproduce the server crash.  Does this only happen during Russian Roulette LR or No Scope LR or both?

**Comment by Caaine** [comment]
"SM_Hosties v2" (2.2.3)
Build:  f63eda 

SourceMod 1.8.0.5928

I can not say exactly when the server crashes .. no error's ... test later the lr's

**Comment by Bara20** [comment]
https://forums.alliedmods.net/showthread.php?p=2447339#post2447339

**Comment by data-bomb** [comment]
Unable to replicate. Closing issue. @Caaine please re-open if you have an exact sequence that will generate the crash.
