### ISSUE TITLE
undefined symbol 

### ISSUE THREAD

**Issue by RED4911** [dataviruset/sm-hosties#68]
//SourceMod Batch Compiler
// by the SourceMod Dev Team

//// sm_hosties.sp
//
// hosties/gamedescription.sp(61) : error 017: undefined symbol "SteamWorks_SetG
ameDescription"
// hosties/gamedescription.sp(73) : error 017: undefined symbol "SteamWorks_SetG
ameDescription"
// hosties/freekillers.sp(265) : error 017: undefined symbol "SBBanPlayer"
// hosties/gunsafety.sp(419) : error 017: undefined symbol "SBBanPlayer"
// hosties/gunsafety.sp(433) : error 017: undefined symbol "SBBanPlayer"
//
// 5 Errors.
//
// Compilation Time: 1,66 sec
// ----------------------------------------

Press enter to exit ...

**Comment by shanapu** [comment]
https://forums.alliedmods.net/showthread.php?t=276863

> 
> 1. Unzip SourceMod to some folder
> 2. Download the sm-hosties main branch or sm-hosties beta branch into the same folder
> 3. Download all the include files into your addons/sourcemod/scripting/include directory.
> EmitSoundAny: https://raw.githubusercontent.com/powerlord/sourcemod-snippets/master/scripting/include/emitsoundany.inc
> SteamWorks: https://github.com/KyleSanderson/SteamWorks/raw/master/Pawn/includes/SteamWorks.inc
> SourceBans: https://github.com/GameConnect/sourcebansv1/raw/master/game_upload/addons/sourcemod/scripting/include/sourcebans.inc
> 4. Compile sm_hosties.sp in the folder (Windows: cmd prompt window and navigate to addons/sourcemod/scripting and then "compile sm_hosties.sp")
> 5. Replace compiled sm_hosties.smx on server
> 6. Replace translations file on server

**Comment by RED4911** [comment]
Thx!!! 
I instead of "Soursbans" use "SourceBans - Material Design", how to fix for it ?

https://github.com/CrazyHackGUT/SB_Material_Design/tree/master

**Comment by shanapu** [comment]
I'm not familiar with materialadmin, but I assume you have to edit the hosties code to replace all old sourcebans natives (e.g SBBanPlayer) with their equivalent of materialadmin.

**Comment by RED4911** [comment]
[SM] Unable to load plugin "MyJailbreak/warden.smx": Could not find required plugin "basecomm" ?

**Comment by data-bomb** [comment]
Closing bug report.  Issue resolved through compilation instructions.
