### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by MindaugasR** [dataviruset/sm-hosties#69]
I don't know how to call in title, so just wrote "bug",

It just started yesturday, before was everything ok. No new plugins added, nothing special changed, just translated texts. Now I get this error:

> L 03/10/2017 - 20:10:23: SourceMod error session started
> L 03/10/2017 - 20:10:23: Info (map "workshop/467648061/jb_buyukisyan_son") (file "errors_20170310.log")
> L 03/10/2017 - 20:10:23: [SM] Exception reported: Handle 670e0872 is invalid (error 3)
> L 03/10/2017 - 20:10:23: [SM] Blaming: sm_hosties.smx
> L 03/10/2017 - 20:10:23: [SM] Call stack trace:
> L 03/10/2017 - 20:10:23: [SM]   [0] CloseHandle
> L 03/10/2017 - 20:10:23: [SM]   [1] Line 258, hosties/muteprisoners.sp::MutePrisoners_RoundEnd
> L 03/10/2017 - 21:00:52: Error log file session closed.

It's happens sometimes, not all the time. Only a few times this show up.

**Comment by data-bomb** [comment]
This issue seems to be caused by not upgrading to the latest version of SM Hosties.  Upgrade and the error should stop.
