### ISSUE TITLE
[CS:GO] Beacons Not Working Correctly

### ISSUE THREAD

**Issue by data-bomb** [dataviruset/sm-hosties#72]
Needs investigation
https://forums.alliedmods.net/showthread.php?t=289621

**Comment by mrkos9i4ok** [comment]
Work in master branch
in beta don't work

**Comment by Bara20** [comment]
With some LRs or all? @mrkos9i4ok

**Comment by mrkos9i4ok** [comment]
likely all

**Comment by mrkos9i4ok** [comment]
All games!

**Comment by mrkos9i4ok** [comment]
Help Beams nice worked
Beacon no sound,no nothing

**Comment by mrkos9i4ok** [comment]
Check pls : 3
https://youtu.be/mIBZdOwJi7U

**Comment by data-bomb** [comment]
Hmm, good investigative work.. this is the exact behavior I would expect when you remove the modulus operator.

**Comment by data-bomb** [comment]
Please let us know if the latest commit fixes the beacons

**Comment by data-bomb** [comment]
Fixed https://github.com/dataviruset/sm-hosties/pull/85
