### ISSUE TITLE
[CS:GO] Server Crash with Zeus

### ISSUE THREAD

**Issue by data-bomb** [dataviruset/sm-hosties#73]
https://forums.alliedmods.net/showthread.php?t=298446

Appears as if Zeus is still present after the call to StripAllWeapons

https://github.com/dataviruset/sm-hosties/blob/master/addons/sourcemod/scripting/include/hosties.inc#L71
So one way to fix this is to fix StripAllWeapons to remove the Zeus.

Another possibility is to modify the SDK Hook for deciding weapon usage to stop anything but the knife and Shot4Shot weapons to be used during the LR.
https://github.com/dataviruset/sm-hosties/blob/master/addons/sourcemod/scripting/hosties/lastrequest.sp#L2020

**Comment by Bara20** [comment]
I'll take a look in the next days if ive time.

**Comment by Bara20** [comment]
Should be fixed with this pr for the beta branch: https://github.com/dataviruset/sm-hosties/pull/74

**Comment by data-bomb** [comment]
Fixed ( #74 )
