### ISSUE TITLE
Maybe this fix?

### ISSUE THREAD

**Issue by mrkos9i4ok** [dataviruset/sm-hosties#76]
https://github.com/mrkos9i4ok/sm-hosties/commit/5214d6b1c31329b3e9bb57b812052f1583e493ba
https://github.com/mrkos9i4ok/sm-hosties/commit/ae867daf5ca0a7ae1802a1b58eaa6f6280e10849

**Comment by Bara20** [comment]
And that should fix what? It's just a rollback to the old syntax.

**Comment by mrkos9i4ok** [comment]
I did not know, in that code I was made an exit button, which in cs go was not

**Comment by Bara20** [comment]
I've added check for csgo.

**Comment by mrkos9i4ok** [comment]
And what about the fact that not always and not everyone is given gravity or speed in lr games?
