### ISSUE TITLE
Gravity Speed Error

### ISSUE THREAD

**Issue by mrkos9i4ok** [dataviruset/sm-hosties#79]
In lr games:
-LR_KnifeFight_HiSpeed
-LR_KnifeFight_LowGrav
-LR_Dodgeball
Gravity or Speed work only for CT team

**Comment by data-bomb** [comment]
Although I reviewed the code in these areas, there is no evidence that Hosties is the cause.  Most likely there is a conflict with another plugin which is setting the gravity and speed to different values after Hosties sets the values desired for the LR.

**Comment by mrkos9i4ok** [comment]
I check all 999 time and I even put to server plugin which the set all standart
