### ISSUE TITLE
Hot Potato crashes server CSGO

### ISSUE THREAD

**Issue by devu4** [dataviruset/sm-hosties#88]
As soon as a LRing players chooses a CT in hot potato, the server crash. It's been happening since the last CSGO update. Accelerator says 'This crash was caused by a plugin trying to spawn an incorrectly configured entity.' 

Nothing in error logs or console.log

Anyone else experiencing this same issue or is it just my server?

**Comment by Bara20** [comment]
Same here, but currently no time to fix it.

**Comment by devu4** [comment]
Seems the issue is createentitybyname, I change to GivePlayerItem(LR_Player_Prisoner, "weapon_deagle"); and the crashes have stopped.

Might have something to do with this: https://forums.alliedmods.net/showthread.php?p=2544465#post2544465

**Comment by data-bomb** [comment]
@devu4 Good work hunting this down! https://github.com/dataviruset/sm-hosties/pull/89 will resolve this shortly.
