### ISSUE TITLE
Error trying to compile lastrequest.sp please help

### ISSUE THREAD

**Issue by RnYPT** [dataviruset/sm-hosties#91]
Hello guys, i get this mensage when i try to compile lastrequest.sp.

//SourceMod Batch Compiler
// by the SourceMod Dev Team

//// lastrequest.sp
//
// C:\Users\ktm-t\Desktop\smod\addons\sourcemod\scripting\lastrequest.sp(283) : error 017: undefined symbol "MAX_DISPLAYNAME_SIZE"
// C:\Users\ktm-t\Desktop\smod\addons\sourcemod\scripting\lastrequest.sp(283) : error 009: invalid array size (negative, zero or out of bounds)
// C:\Users\ktm-t\Desktop\smod\addons\sourcemod\scripting\lastrequest.sp(669) : error 017: undefined symbol "TopMenuAction_DisplayOption"
// C:\Users\ktm-t\Desktop\smod\addons\sourcemod\scripting\lastrequest.sp(673) : error 017: undefined symbol "TopMenuAction_SelectOption"
// C:\Users\ktm-t\Desktop\smod\addons\sourcemod\scripting\lastrequest.sp(723) : error 017: undefined symbol "MAX_DISPLAYNAME_SIZE"
// C:\Users\ktm-t\Desktop\smod\addons\sourcemod\scripting\lastrequest.sp(723) : error 009: invalid array size (negative, zero or out of bounds)
// C:\Users\ktm-t\Desktop\smod\addons\sourcemod\scripting\lastrequest.sp(723) : error 036: empty statement
// C:\Users\ktm-t\Desktop\smod\addons\sourcemod\scripting\lastrequest.sp(723) : fatal error 190: too many error messages on one line
//
// Compilation aborted.
// 8 Errors.
//
// Compilation Time: 0,42 sec
// ----------------------------------------

Press enter to exit ..

**Comment by RnYPT** [comment]
Ok i get it, i have to compile sm_hosties instead of only lastrequest, but when i try to compile sm_hosties.sp i get this 
https://gyazo.com/6d6f392a928bea53c269ae02a562ce0c

**Comment by dataviruset** [comment]
That's because the compiler can't find the natives from SourceBans and SteamWorks. You need to add the required include files for those plugins in your include folder.

https://forums.alliedmods.net/showthread.php?t=229556
https://forums.alliedmods.net/forumdisplay.php?f=152
